version: "3.7"
services:

  neo4j:
    image: neo4j:4.0-enterprise
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data:/data
      - ./import:/var/lib/neo4j/import
    environment:
      NEO4J_AUTH: none
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
